name: vue-app
services:
  web:
    image: httpd:latest  # Use Apache HTTP Server
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./:/usr/local/apache2/htdocs/  # Serve static files from the current directory
