name: vue-app
services:
  web:
    image: httpd:latest  # Use the official Apache HTTP Server image
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./dist:/usr/local/apache2/htdocs/:ro  # Mount the 'dist' folder to Apache's web root
      - ./dist/.htaccess:/usr/local/apache2/htdocs/.htaccess:ro  # Add the .htaccess file
